### ISSUE TITLE
Is the background service open source? Or the minimum available service

### ISSUE THREAD

**Issue by applyfly** [nuxtlabs/vue-telescope-website#53]
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/53924395/195542733-15436ced-3a95-485a-a566-823480540555.png">

**Comment by helloshaohua** [comment]
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/53924395/195542629-1e296cd3-f565-46c9-b053-2f51d33706ef.png">
